### ISSUE TITLE
Named resource search should be case-insensitive

### ISSUE THREAD

**Issue by biggnome** [avaraline/Avara#146] opened 2021-01-28 00:16 UTC
This is due to a minor typographical error in the original resource where the "d" in what should be "Bomb Deposit.pict" is lowercase which prevents that level from loading. It's a simple fix to the .r file with a hex editor, but there you go.

**Comment by assertivist** [comment] 2021-01-28 01:55
Hey, thanks for the report!!

This is actually something that we need to fix in the resource loading code. The .r files are sacrosanct, if the original did it, we should do it that way. The resource parsing and handling was all done as part of the port because those would have been Mac Toolbox calls. Anyway the problem is here:

https://github.com/avaraline/Avara/blob/master/src/compat/Resource.cpp#L62

This needs to be case insensitive (and also should probably use `strcmp` anyway).

There are other levels that don't load correctly because of this, including Hazel's from T plus 5.

**Comment by Xiphunon** [comment] 2021-02-02 11:37
Hi, I'd love to work on this. I am new to open source projects and this issue seems easy enough with the guidelines you have given.

**Comment by assertivist** [comment] 2021-02-02 15:34
@Xiphunon feel free! Just open a Pull Request when you get it working.

**Comment by assertivist** [comment] 2021-02-02 17:19
@Xiphunon Thanks for the contribution! Closed in #149 !

**Closed by assertivist** 2021-02-02 17:19 UTC
Labels: bug, good first issue
